### ISSUE TITLE
Add bindable sink for write transactions

### ISSUE THREAD

**Issue by icanzilb** [RxSwiftCommunity/RxRealm#12]
Create a bindable sink for when the user needs to save objects to the realm. E.g.:

``` swift
    ... blah fetch json ... map to objects ...
            .subscribeNext {objects in
                let realm = try! Realm()
                try! realm.write {
                    realm.add(objects, update: true)
                }
            }

```

**Comment by sergdort** [comment]
Hi, found there problem while writing tests:

So, since we decided to have `static fun rx_add..`

We will not have the reference to `Realm` instance

but in tests we are using in memory `Realm`
and in the `rx_add` we are doing 

``` swift
let realm = try! Realm()
 try! realm.write {
    realm.add(object)
}
```

which will create `Realm` with `defaultConfiguration` and will store objects locally (and tests will not pass because it will store objects into another DB)

So I'm thinking, wouldn't this be a problem in some real world project, if some body use `Realm` with in memory configuration, but rx_add would store it in local DB :)

**Comment by icanzilb** [comment]
now that you ask ... we should be able to allow the user to specify the realm they want to write to ... writing only to the default realm ofc doesn't make sense..

**Comment by icanzilb** [comment]
it seems it would be better to move `rx_add` as an instance variable on `Realm` - this way the user will have the chance to get the realm instance they want to save to and just bind the pending objects to its `rx_add` - how about that idea?

**Comment by icanzilb** [comment]
This has been merged via https://github.com/RxSwiftCommunity/RxRealm/pull/17

**Comment by icanzilb** [comment]
I'm reopening this since multi-threaded usage proves to be a bit harder than intially thought - will need to adjust a bit the code for that

**Comment by icanzilb** [comment]
@sergdort I merged everything to `master` and I'll release a new Pod version, thanks !
