### ISSUE TITLE
Deleting row => asObservableChangeset

### ISSUE THREAD

**Issue by remirobert** [RxSwiftCommunity/RxRealm#28]
Hello,

I have a strange behaviour, I have a observer on for **asObservableChangeset** : 

``` swift
realm.objects(Message).asObservableChangeset()
   .subscribeNext {result, changes in
         if let changes = changes {
             print("[🏵🐹] deleted: \(changes.deleted) inserted: \(changes.inserted) updated: \(changes.updated)")
         } else {
             print("get results result :\(result.count)")
         }
}.addDisposableTo(self.disposeBag)
```

when I deleted a row, I got a deleted change offset but also an inserted offset.
Also the index is always = 0 
Is it normal to receive a inserted index, when I delete a row ?

**Comment by icanzilb** [comment]
no I wouldn't say it's normal, do you have a piece of code that can reproduce it? 

there's a unit test to show you the expected behavior:

https://github.com/RxSwiftCommunity/RxRealm/blob/master/Example/RxRealm_Tests/RxRealmResultsTests.swift#L105

and the expected result:

https://github.com/RxSwiftCommunity/RxRealm/blob/master/Example/RxRealm_Tests/RxRealmResultsTests.swift#L120
