### ISSUE TITLE
Use of undeclared type 'ObservableType'

### ISSUE THREAD

**Issue by miff** [RxSwiftCommunity/RxRealm#53]
Works in simulator, but fail on device. Tested on 6, 6s and iPad 2013.

**Comment by icanzilb** [comment]
hi, can you provide more details - what is not working exactly? have you tried if the demo app from this repo works for you?

**Comment by miff** [comment]
Usage of undeclared types in RxRealm.swift file. 
<img width="241" alt="screen shot 2016-12-22 at 12 11 37 am" src="https://cloud.githubusercontent.com/assets/469459/21409564/47f440ca-c7db-11e6-95f8-f9555ae394b9.png">

**Comment by icanzilb** [comment]
In what way do you import RxRealm in your project? CocoaPods or some other way?

**Comment by miff** [comment]
Manually build from https://github.com/ReactiveX/RxSwift

**Comment by icanzilb** [comment]
This is an interesting problem but I'm not sure how to help you with this one. The types you see reported as missing namely `Reactive`, `AnyObserver`, and `Observable` are all the types RxRealm uses from RxSwift. For some reason in your setup RxRealm can't import RxSwift. If it happens only when you build for the device as you say I'd check the project's build settings because I have no idea what else it could be..

**Comment by miff** [comment]
Thanks, am also confused... i will try again with different build

**Comment by miff** [comment]
Thanks Marin,
but build RxSwift with CocoaPod do the job.
