### ISSUE TITLE
adding RxRealm on swift3

### ISSUE THREAD

**Issue by Fouda** [RxSwiftCommunity/RxRealm#96]
I couldn't add RxRealm on Swift3 xcode8.3
<img width="269" alt="screen shot 2017-10-27 at 2 15 10 pm" src="https://user-images.githubusercontent.com/12399604/32105699-a435a0f8-bb29-11e7-8cf9-998a70a42e34.png">

I get this error when I install pod
<img width="616" alt="screen shot 2017-10-27 at 2 15 24 pm" src="https://user-images.githubusercontent.com/12399604/32105712-ae95e3f0-bb29-11e7-9865-4073c1f67afd.png">

**Comment by icanzilb** [comment]
Is your project swift 3.2 ?

**Comment by Fouda** [comment]
Swift 3
<img width="616" alt="screen shot 2017-10-27 at 2 21 16 pm" src="https://user-images.githubusercontent.com/12399604/32105923-81c2f998-bb2a-11e7-9d3a-39c0a072090c.png">

**Comment by icanzilb** [comment]
well, you need to resolve your conflicts as described by cocoapods's resolver - in your Podfile, you require RealmSwift 3.0.1 which is swift4/swift 3.2, and RxRealm 0.6.0, which is swift 3.1 ... I can't tell which swift version you use in your project from the screenshot you pasted above, but at least the RealmSwift and RxRealm should match. 

If you have swift4, use RealmSwift 3+ and RxRealm 0.7+, otherwise RealmSwift 2.+ and RxRealm 0.6

**Comment by Fouda** [comment]
using swift3.2, can you specify the version of each pod :

<img width="271" alt="screen shot 2017-10-27 at 2 48 21 pm" src="https://user-images.githubusercontent.com/12399604/32107236-4ab5d5f2-bb2e-11e7-8b51-a8c99349c87f.png">

**Comment by icanzilb** [comment]
No idea, have not built for swift 3.2
